#!/bin/sh

rm -rf libspatialite.xcframework

operationg_systems=(ios macos sim)
architectures=(arm64)

command="xcodebuild -create-xcframework -output libspatialite.xcframework"
    
for arch in "${architectures[@]}"; do
	for os in "${operationg_systems[@]}"; do
		if [ -d "build/$arch-$os" ]; then
			echo "Building $arch-$os"
			cd "build/$arch-$os/lib"
			rm -f libspatialiteall.a
			libtool -o libspatialiteall.a *.a
			cd -
			command="$command -library build/$arch-$os/lib/libspatialiteall.a -headers include/"
		else
			echo "Skipping $arch-$os"
		fi
	done
done

# Make framework
$command

zip -r libspatialite.xcframework.zip libspatialite.xcframework
